# @package _global_
# module:
#   _target_: emg2qwerty.lightning.TDSConvCTCModule
#   in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
#   mlp_features: [384]
#   block_channels: [24, 24, 24, 24]
#   kernel_width: 32  # Total temporal receptive field of 125 samples given 4 layers

module:
  # CNN + LSTM Module
  _target_: emg2qwerty.lightning.CNNLSTMModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  cnn_channels: [32, 64, 128, 256]
  lstm_hidden_size: 512
  lstm_num_layers: 2
  dropout: 0.2

# module:
#   # CNN + RNN Module
#   _target_: emg2qwerty.lightning.CNNRNNModule
#   in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
#   cnn_channels: [32, 64, 128, 256]
#   kernel_size: 3
#   rnn_hidden_size: 512
#   rnn_num_layers: 2
#   dropout: 0.2
#   adaptive_pool_size: 2


datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
